# https://docs.travis-ci.com/user/languages/python/
language: python

# https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
branches:
  only:
    - master

# https://docs.travis-ci.com/user/encryption-keys/
env:
  global:
    - secure: "Pn1FnXJM8rsXp8+rkhwMYWazmElqM979PWVjmJ7CxLi/Dw++R0tj1zjZfkyxPW4G26fZRd4W5pvw0BAk1ymqKbBR0TlHNi9uSMZVHNNZMGW0WG1WF2ucSpe+WZWMfgbiUXA1IqqkjGjUYsBloeMJ4u+c7H5YIA4vwDIyIoh8qTKu6ggplRlEWGuKauDDRZoXabPFwAo/YnyeQrdAbShvidvObVIUA2aYE+hfpqhgYBEd8gdpD3OMTOu3bRGP4z+c4Dp1l8lsixvGrA+ikzKBgQqWDYrpaHlnOTX8sheQAmOffzikWFn6YDNp1V1IJHyZuBcD0LPJeKVLhH3Jkt2jlhXYzSH2/LYAWE8x0oFHCl5vy3tdfc9TWdRYPEinmKpZNR3SaDveLk7/9J52ubs0vWnGSr83ABDRlcsyerBepVj5XUq8vQReRd1Io9BMuvjr/DKZ971RRGRGYz0CZzWip+ANNAUiv0MZn46rgKbtUZyIE1tMvFsGL1MTz+oy883fcdUV+xt/45KQPgy75nWmI6hLr7ZY99EFnAbNDG33D47YFz56YJ3M+vssmNhHvGpserWfaS8qpvT8v2tcSf+QPhZh1wrVL+rAG9F8x95wNe4nMJP/CC4Nx1KtRj8tGZK83dRoUeoD1GOXn7pYQP+NNffXlwGGKsNRxcirerko+T8="

# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
install:
  - pip install git+https://github.com/adblockplus/python-abp
before_script:
  - export TZ=America/Maceio
 
 require 'spec_helper'
context "during the week after 11:00am for Morning Follow Up Call" do
  before do
    valid_prospect_params["treatment_enquiry_form"]["contact_time"] = "10:00 am"
    freeze_time = Time.local(2015, 11, 18, 11, 01, 0)
    change_time(freeze_time)
    post :create_prospect, valid_prospect_params
    reset_time
  end

  it "creates follow up activities" do
    expect(prospect_followup_activities).to eq(3)
  end

  it "creates follow_up_call for the next day in the morning " do
    expect(first_call.scheduled_for.to_s).to  eq("2015-11-19 10:00:00 +1100")
  end
end
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "TravisCI"
  - git config --global push.default "matching"

# https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step
script:
  - git clone -b filtro $DEPLOY_REPO output
  - flrender -i easylistbrasil=. easylistbrasil.template output/easylistbrasil.txt
  - cd output && git add --all . && git commit -m "Publishing revision $(git --git-dir ../.git rev-parse --short HEAD)" && git push --force origin filtro
